Поправила задание 8, но оно немного странновато работает 😅
typefoxes/SkillBoxHW pull request #1
Opened 2021-01-24 12:53 UTC by typefoxes

Сортировка странная...Но работает же 😅

2021-01-25 12:48 UTC, ios-review requested changes
За ПР (пул реквест) 🔥🔥🔥

По заданиям еще поработаем)

2021-01-25 12:48 UTC, ios-review commented on mod15/ViewController.swift
> +    @IBAction func clearButton(_ sender: Any) {
Параметр sender не используется.
Во всех функциях, где он не нужен, его можно удалить.

2021-01-25 12:48 UTC, ios-review commented on mod15/ViewController.swift
> +//  Задание1:  pure function - «чистая функция», она не изменяет тип данных, которые были у нее на входе.Это делает код более лаконичным, с ней не нужно копипастить код, можно просто вызвать функцию.
Не совсем понял определение.
Не изменяет тип данных?
`func doSome(a: String) -> Int {}`
Какой бы не была реализация этой функции, она не изменит тип данных, которые были на входе и на выходе.

```
class Test {
    private var a = 0

    func dirty() -> Int {
        self.a = 10
        return self.a
    }

    func pure(b: Int) -> Int {
        return b + 10
    }
}
```

Вот здесь одна функция чистая, другая нет.
В чем разница между ними?

2021-01-25 12:48 UTC, ios-review commented on mod15/ViewController.swift
> +    }
Функция всегда сравнивает первый и второй элементы из массива numbers.
А должна сравнивать переданные в функцию аргументы.

2021-01-25 12:48 UTC, ios-review commented on mod15/ViewController.swift
> +    }
Строку 76 можно записать еще короче.
Как?

2021-01-25 12:48 UTC, ios-review commented on mod15/ViewController.swift
> +        }
```
func task6(execute: () -> Void) {
    DispatchQueue.main.asyncAfter(deadline: .now() + 2, execute: execute)
}

task6 { self.label.text = "2 second later" }
```

2021-01-25 12:48 UTC, ios-review commented on mod15/ViewController.swift
> +
У таких операторов тоже 2 операнда?

2021-01-25 12:48 UTC, ios-review commented on mod15/ViewController.swift
>      }
Такой код уже есть в clearButton.
Можно тут вызвать эту функцию.

2021-01-26 09:01 UTC, typefoxes commented on mod15/ViewController.swift
>      }
Да, действительно)

2021-01-26 09:01 UTC, typefoxes commented on mod15/ViewController.swift
> +
- infix определять свою логику для бинарных операторов (+-)
- prefix определить свою логику для унарного минуса (только один операнд)
- postfix определить свою логику оператора, который следует за операндом (b!) (только один операнд)

2021-01-26 09:01 UTC, typefoxes commented on mod15/ViewController.swift
> +    }
Полагаю у меня это получилось в коде, функция работает также как и работала изначально =) + сортирует по-порядку

2021-01-26 09:01 UTC, typefoxes commented on mod15/ViewController.swift
> +//  Задание1:  pure function - «чистая функция», она не изменяет тип данных, которые были у нее на входе.Это делает код более лаконичным, с ней не нужно копипастить код, можно просто вызвать функцию.
В коде определение написала более развернуто и понятно.

2021-01-26 09:01 UTC, typefoxes commented on mod15/ViewController.swift
> +    @IBAction func clearButton(_ sender: Any) {
В коде убрала везде, где было нужно.

2021-01-27 06:47 UTC, ios-review approved these changes
Классная доработка👍
Особо отмечу определение чистой функции.
Прям аааа)

Пул реквест можно мержить (merge).
Это значит, что изменения в этой ветки будут объединены с изменениями в главной ветке main.

2021-01-27 06:47 UTC, ios-review commented on mod15/ViewController.swift
> +//  Задание1:  Функция считается чистой, когда не производит никаких побочных эффектов и когда она не полагается на какое-либо внешнее состояние. Основная мысль заключается в том, что она всегда буде
Академическое определение)

Круто😎
Молодец🔥🔥🔥

2021-01-27 06:47 UTC, ios-review commented on mod15/ViewController.swift
>      }
Код можно было реализовать сразу в соответствующих @IBAction функциях.

2021-01-27 06:52 UTC, merged